#!/usr/bin/env sh
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --config config/commitlint.config.js --edit "$1"
commit_number=$(git rev-list --all --count)
new_message="[$commit_number] $(cat "$1")"

echo "$new_message" > "$1"