name: code-quality

on: [push, pull_request]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    env: # Define environment variables for the job
      GSAP_API_KEY: ${{ secrets.GSAP_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      # - name: Install Bun
      #   run: |
      #     curl -fsSL https://bun.sh/install | bash
      #     echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # - name: Install dependencies
      #   run: bun install

      # - name: Run ESLint
      # run: bun run lint

      ##- name: Run Prettier
      # run: bun run pretty

      # - name: Build project
      #   run: bun run build
